global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
# California Housing API metrics
- job_name: 'housing-api'
  static_configs:
  - targets: [ 'housing-api:8000' ]
  metrics_path: '/prometheus'
  scrape_interval: 10s
  scrape_timeout: 5s

# Prometheus itself
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
