{
 "title": "California Housing API - Basic Monitoring",
 "tags": [
  "california-housing",
  "mlops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Prediction Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(housing_prediction_requests_total)"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(housing_api_requests_http_request_duration_seconds_sum{handler=~\"/predict.*\",status=\"200\"}[5m]) / rate(housing_api_requests_http_request_duration_seconds_count{handler=~\"/predict.*\",status=\"200\"}[5m]) * 1000",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Model Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "housing_model_loaded" }
   ]
  },
  {
   "title": "Total Model Predictions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "housing_model_predictions_total"
    }
   ]
  },
  {
   "title": "Model Retraining Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "housing_retraining_triggered_total"
    }
   ]
  }
 ]
}