apiVersion: 1

deleteDatasources:
- name: Prometheus
  orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  uid: prometheus-datasource
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
  jsonData:
    httpMethod: GET
    prometheusType: Prometheus
    prometheusVersion: 2.40.0
  secureJsonData: {}
