name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install flake8 pytest

      # Step 4: Lint the code
      - name: Lint code
        run: flake8 src/

  test:
    needs: lint  # Run this job only if lint succeeds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    
    - name: Make test script executable
      run: chmod +x run_tests.sh

    - name: Run tests using script
      run: ./run_tests.sh
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.9'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  dockerize:
      needs: test  # Run this job only if test succeeds
      runs-on: ubuntu-latest
      steps:
        # Step 1: Checkout the code
        - uses: actions/checkout@v2

        # Step 2: Debug build context
        - name: List Files in Build Context
          run: ls -la

        # Step 3: Debug Dockerfile presence
        - name: Check Dockerfile
          run: |
            if [ ! -f Dockerfile ]; then
              echo "Dockerfile not found!"
              exit 1
            fi

        # Step 4: Build Docker image
        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/california-housing-api:latest .

        # Step 5: Push Docker image to Docker Hub
        - name: Push Docker Image
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push ${{ secrets.DOCKER_USERNAME }}/california-housing-api:latest
